# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "java/fmi4j/build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "java/fmi4j/build.gradle" }}

      - run: cd java/fmi4j && ./gradlew clean build

      - run: cd java/fmi4j && ./gradlew shadowJar

      - store_artifacts:
          path: java/fmi4j/fmu-driver/build/libs/fmu-driver.jar
          destination: fmu-driver.jar
